# Generated by Django 2.2.3 on 2020-01-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('Registration_ID', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=20)),
                ('MiddelName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=10)),
                ('MobileNo', models.IntegerField()),
                ('Qualification', models.CharField(max_length=20)),
                ('Reason_For_Visite', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Registration',
            },
        ),
    ]
